# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: test
    value: 'WyJ0ZXN0MSIsICJ0ZXN0MiJd'
steps:

- script: |
    modified_dirs_json=$(echo $(test) | base64 --decode)
    modified_dirs=$(echo $modified_dirs_json | jq -r '.[]')

    for dir in $modified_dirs; do
      echo $dir
    done
  displayName: 'Run a multi-line script'
